[package]
name = "breach"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.22.1"
tokio = { version = "1.37.0", features = ["full"] }
windows = { version = "0.56.0", features = ["Media_Control", "Storage_Streams", "Graphics_Imaging"] }
